In [5]:
import datetime
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="darkgrid")
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示
from zipfile import ZipFile

In [2]:
import pickle
# 第一次运行时 usingSaved=False，生成临时文件后改为True
usingSaved=True

In [7]:
#读取item
if not usingSaved:
    output = open('item_attr.pkl', 'wb')
    myzip=ZipFile('./data/Antai_AE_round1_item_attr_20190626.zip')
    f=myzip.open('Antai_AE_round1_item_attr_20190626.csv')
    item_attr=pd.read_csv(f)
    f.close()
    myzip.close()
    pickle.dump(item_attr, output)
    output.close()
else:
    item_attr = pickle.load(open('item_attr.pkl', 'rb'), encoding='iso-8859-1')
#     item_attr = pickle.load(open('item_attr.pkl', 'rb'))

In [8]:
#读取train  
if not usingSaved:
    output = open('train.pkl', 'wb')
    myzip=ZipFile('./data/Antai_AE_round1_train_20190626.zip')
    f=myzip.open('Antai_AE_round1_train_20190626.csv')
    train=pd.read_csv(f)
    f.close()
    myzip.close()
    train['create_order_time'] = train.create_order_time.apply(lambda x:pd.to_datetime(x))
    train['hour']=train['create_order_time'].dt.hour
    train['date']=train['create_order_time'].dt.day
    train['month']=train['create_order_time'].dt.month
    train['year']=train['create_order_time'].dt.year
    train['month-date'] = train.month.astype(str)+'-'+train.date.astype(str)
    train['count'] = 1
    train['dayofweek']=train['create_order_time'].dt.dayofweek
    train['isweekend']=train['dayofweek'].apply(lambda x:0 if x<5 else 1)
    pickle.dump(train, output)
    output.close()
else:
    train = pickle.load(open('train.pkl', 'rb'),encoding='iso-8859-1')
#     train = pickle.load(open('train.pkl', 'rb'))

In [9]:
#读取test
if not usingSaved:
    output = open('test.pkl', 'wb')
    test=pd.read_csv('./data/Antai_AE_round1_test_20190626.csv')
    test['create_order_time'] = test.create_order_time.apply(lambda x:pd.to_datetime(x))
    test['hour']=test['create_order_time'].dt.hour
    test['date']=test['create_order_time'].dt.day
    test['month']=test['create_order_time'].dt.month
    test['year']=test['create_order_time'].dt.year
    test['count'] = 1
    test['month-date'] = test.month.astype(str)+'-'+test.date.astype(str)
    test['dayofweek']=test['create_order_time'].dt.dayofweek
    test['isweekend']=test['dayofweek'].apply(lambda x:0 if x<5 else 1)
    pickle.dump(test, output)
    output.close()
else:
    test = pickle.load(open('test.pkl', 'rb'), encoding='iso-8859-1')
submit = pd.read_csv('./data/Antai_AE_round1_submit_20190715.csv')
#     test = pickle.load(open('test.pkl', 'rb'))

In [10]:
trainyy = train[train.buyer_country_id =='yy']

In [11]:
submit.head()

,152,343131,2140290,2600629,1554159,12211445,776612,1630164,3901301,8353580,...,2327622,2014295,5076158,5042708,818444,10451831,4333367,9437487,8469786,9465790
0,282,8988184,2210260,96479,4052816,7982989,11143899,10070236,2002400,8757854,...,5630838,8607737,7740462,7028968,9167824,12938507,6399956,3109441,10636176,6255625
1,321,11140901,4618502,9666424,421308,8443514,12341414,4133929,4374880,9104983,...,12975999,10793761,7524523,666863,204808,8893340,7431033,1773069,12970909,9373627
2,809,692592,9851186,5206030,1210732,6016462,6971778,11615323,7263674,10901782,...,3227122,10539551,2802000,8251066,9515496,7065316,11997137,4438427,6567724,7212577
3,870,8361014,2327622,5481981,7530272,11680535,6555249,6137574,914424,10445923,...,8757854,10578287,10715090,7176446,3165153,10144005,8753413,2800387,12152573,1068526
4,2410,6320318,7525163,10734361,9050161,11309657,686434,10621679,11493273,12031376,...,7999857,6024506,7726279,245564,8636658,7684124,5386552,956425,5701392,7358804

In [12]:
test.head()

,buyer_country_id,buyer_admin_id,item_id,create_order_time,irank,hour,date,month,year,count,month-date,dayofweek,isweekend
0,yy,1061132,189045,2018-07-17 07:43:40,18,7,17,7,2018,1,7-17,1,0
1,yy,1081430,10713670,2018-07-17 09:43:15,8,9,17,7,2018,1,7-17,1,0
2,yy,1918135,10546322,2018-07-17 11:11:34,9,11,17,7,2018,1,7-17,1,0
3,yy,103277,5199603,2018-07-17 13:27:44,24,13,17,7,2018,1,7-17,1,0
4,yy,103277,2477273,2018-07-17 13:27:44,22,13,17,7,2018,1,7-17,1,0

In [13]:
trainyy.head()

,buyer_country_id,buyer_admin_id,item_id,create_order_time,irank,hour,date,month,year,month-date,count,dayofweek,isweekend
2,yy,101887,3,2018-08-27 08:31:26,3,8,27,8,2018,8-27,1,0,0
9,yy,288460,6,2018-08-31 13:41:25,11,13,31,8,2018,8-31,1,4,0
10,yy,341958,6,2018-08-31 15:42:10,1,15,31,8,2018,8-31,1,4,0
12,yy,12849617,6,2018-08-09 04:10:36,17,4,9,8,2018,8-9,1,3,0
16,yy,770888,6,2018-08-31 23:33:54,12,23,31,8,2018,8-31,1,4,0

In [14]:
trainyy.buyer_admin_id.unique().shape

(138678,)

In [15]:
trainyy.item_id.unique().shape

(926771,)

In [16]:
merge_yy = pd.concat([trainyy,test])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [17]:
merge_yy.item_id.unique().shape,merge_yy.buyer_admin_id.unique().shape

((972388,), (150076,))

In [18]:
merge_yy.head()

,buyer_admin_id,buyer_country_id,count,create_order_time,date,dayofweek,hour,irank,isweekend,item_id,month,month-date,year
2,101887,yy,1,2018-08-27 08:31:26,27,0,8,3,0,3,8,8-27,2018
9,288460,yy,1,2018-08-31 13:41:25,31,4,13,11,0,6,8,8-31,2018
10,341958,yy,1,2018-08-31 15:42:10,31,4,15,1,0,6,8,8-31,2018
12,12849617,yy,1,2018-08-09 04:10:36,9,3,4,17,0,6,8,8-9,2018
16,770888,yy,1,2018-08-31 23:33:54,31,4,23,12,0,6,8,8-31,2018

In [19]:
import sys
import random
import math
import os
from operator import itemgetter

from collections import defaultdict

random.seed(0)

class UserBasedCF(object):
    ''' TopN recommendation - User Based Collaborative Filtering '''

    # 构造函数，用来初始化
    def __init__(self):
        # 定义 训练集 测试集 为字典类型
        self.trainset = {}
        self.testset = {}
        # 训练集用的相似用户数
        self.n_sim_user = 30
        # 推荐Item数量
        self.n_rec_item = 30

        self.user_sim_mat = {}
        self.item_popular = {}
        self.item_count = 0
        # sys.stderr 是用来重定向标准错误信息的
        print ('相似用户数目为 = %d' % self.n_sim_user, file=sys.stderr)
        print ('推荐Item数目为 = %d' %
               self.n_rec_item, file=sys.stderr)

    # 划分训练集和测试集 pivot用来定义训练集和测试集的比例
    def generate_dataset(self, train,test=None, pivot=0.90):
        ''' load rating data and split it to training set and test set '''
        trainset_len = 0
        testset_len = 0
        if test is None:# 随机分配验证机实验 
            print('算法尝试！')
            for line in train.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                # split the data by pivot
                if random.random() < pivot:
                    self.trainset.setdefault(user, {})
                    self.trainset[user][item] = int(rating)
                    trainset_len += 1
                else:
                    self.testset.setdefault(user, {})
                    self.testset[user][item] = int(rating)
                    testset_len += 1
        else:#真正预测
            print('预测尝试！')
            for line in train.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                # split the data by pivot
                self.trainset.setdefault(user, {})
                self.trainset[user][item] = int(rating)
                trainset_len += 1
            del user,item,rating
            for line in test.iterrows():
                user, item, rating = line[1][0],line[1][1],1
                self.testset.setdefault(user, {})
                self.testset[user][item] = int(rating)
                testset_len += 1
            
        print ('split training set and test set succ')
        print ('train set = %s' % trainset_len)
        print ('test set = %s' % testset_len)
    # 建立物品-用户 倒排表
    def calc_user_sim(self):
        ''' calculate user similarity matrix '''
        # build inverse table for item-users
        # key=itemID, value=list of userIDs who have seen this item
        print ('构建物品-用户倒排表中，请等待......', file=sys.stderr)
        item2users = dict()

        # Python 字典(Dictionary) items() 函数以列表返回可遍历的(键, 值) 元组数组
        for user, items in self.trainset.items():
            for item in items:
                # inverse table for item-users
                if item not in item2users:
                    # 根据商品id 构造set() 函数创建一个无序不重复元素集
                    item2users[item] = set()
                # 集合中值为用户id
                # 数值形如
                # {'914': {'1','6','10'}, '3408': {'1'} ......}
                item2users[item].add(user)
                # 记录电影的流行度
                if item not in self.item_popular:
                    self.item_popular[item] = 0
                self.item_popular[item] += 1
        print ('构建物品-用户倒排表成功', file=sys.stderr)

        # save the total item number, which will be used in evaluation
        self.item_count = len(item2users)
        print ('总共被操作过的物品数目为 = %d' % self.item_count, file=sys.stderr)

        # count co-rated items between users
        usersim_mat = self.user_sim_mat

        print ('building user co-rated items matrix...', file=sys.stderr)
        # 令系数矩阵 C[u][v]表示N(u)∩N（v) ，假如用户u和用户v同时属于K个物品对应的用户列表，就有C[u][v]=K
        for item, users in item2users.items():
            for u in users:
                usersim_mat.setdefault(u, defaultdict(int))
                for v in users:
                    if u == v:
                        continue
                    usersim_mat[u][v] += 1
        print ('build user co-rated items matrix succ', file=sys.stderr)

        # calculate similarity matrix
        print ('calculating user similarity matrix...', file=sys.stderr)
        simfactor_count = 0
        PRINT_STEP = 2000000
        # 循环遍历usersim_mat 根据余弦相似度公式计算出用户兴趣相似度
        for u, related_users in usersim_mat.items():
            for v, count in related_users.items():
                # 以下是公式计算过程
                usersim_mat[u][v] = count / math.sqrt(
                    len(self.trainset[u]) * len(self.trainset[v]))
                #计数 并没有什么卵用
                simfactor_count += 1
                if simfactor_count % PRINT_STEP == 0:
                    print ('calculating user similarity factor(%d)' %
                           simfactor_count, file=sys.stderr)

        print ('calculate user similarity matrix(similarity factor) succ',
               file=sys.stderr)
        print ('Total similarity factor number = %d' %
               simfactor_count, file=sys.stderr)
    # 根据用户给予推荐结果
    def recommend(self, user,predict=False):
        '''定义给定K个相似用户和推荐N个商品'''
        K = self.n_sim_user
        N = self.n_rec_item
        # 定义一个字典来存储为用户推荐的电影
        rank = dict()
        
        watched_items = self.trainset[user]
        # sorted() 函数对所有可迭代的对象进行排序操作。 key 指定比较的对象 ，reverse=True 降序
        for similar_user, similarity_factor in sorted(self.user_sim_mat[user].items(),
                                                      key=itemgetter(1), reverse=True)[0:K]:
            for item in self.trainset[similar_user]:
                # 判断 如果这个商品 该用户已经买过 则跳出循环 ##此处不太成立
#                 if item in watched_items:
#                     continue
                # 记录用户对推荐的电影的兴趣度
                rank.setdefault(item, 0)
                rank[item] += similarity_factor
        # return the N best items
        return sorted(rank.items(), key=itemgetter(1), reverse=True)[0:N]
    def predict(self):
        print('Predict start...')

        N = self.n_rec_item
        #  varables for precision and recall
        hit = 0
        rec_count = 0
        test_count = 0
        # varables for coverage
        all_rec_items = set()
        # varables for popularity
        popular_sum = 0
        predict_result=[]
        for i, user in enumerate(self.testset):
            if i % 500 == 0:
                print ('recommended for %d users' % i)
            rec_items = self.recommend(user,predict=True)
            predict_result.append((user,rec_items))
        print('Predict end...')
        return predict_result
    # 计算 准确略，召回率，覆盖率，流行度
    def evaluate(self):

        ''' print evaluation result: precision, recall, coverage and popularity '''
        print ('Evaluation start...', file=sys.stderr)

        N = self.n_rec_item
        #  varables for precision and recall
        #记录推荐正确的电影数
        hit = 0
        #记录推荐电影的总数
        rec_count = 0
        #记录测试数据中总数
        test_count = 0
        # varables for coverage
        all_rec_items = set()
        # varables for popularity
        popular_sum = 0

        for i, user in enumerate(self.trainset):
            if i % 500 == 0:
                print ('recommended for %d users' % i, file=sys.stderr)
            test_items = self.testset.get(user, {})
            rec_items = self.recommend(user,predict=False)
            for item, _ in rec_items:
                if item in test_items:
                    hit += 1
                all_rec_items.add(item)
                popular_sum += math.log(1 + self.item_popular[item])
            rec_count += N
            test_count += len(test_items)
        # 计算准确度
        precision = hit / (1.0 * rec_count)
        # 计算召回率
        recall = hit / (1.0 * test_count)
        # 计算覆盖率
        coverage = len(all_rec_items) / (1.0 * self.item_count)
        #计算流行度
        popularity = popular_sum / (1.0 * rec_count)

        print ('precision=%.4f\trecall=%.4f\tcoverage=%.4f\tpopularity=%.4f' %
               (precision, recall, coverage, popularity), file=sys.stderr)

In [20]:
usercf = UserBasedCF()

相似用户数目为 = 30
推荐Item数目为 = 30

In [21]:
usercf.generate_dataset(merge_yy[['buyer_admin_id','item_id']])

算法尝试！
split training set and test set succ
train set = 2159745
test set = 239954

In [22]:
usercf.calc_user_sim()

构建物品-用户倒排表中，请等待......
构建物品-用户倒排表成功
总共被操作过的物品数目为 = 905532
building user co-rated items matrix...
build user co-rated items matrix succ
calculating user similarity matrix...
calculating user similarity factor(2000000)
calculating user similarity factor(4000000)
calculating user similarity factor(6000000)
calculating user similarity factor(8000000)
calculating user similarity factor(10000000)
calculating user similarity factor(12000000)
calculating user similarity factor(14000000)
calculating user similarity factor(16000000)
calculating user similarity factor(18000000)
calculating user similarity factor(20000000)
calculating user similarity factor(22000000)
calculate user similarity matrix(similarity factor) succ
Total similarity factor number = 23241670

In [23]:
usercf.evaluate()

Evaluation start...
recommended for 0 users
recommended for 500 users
recommended for 1000 users
recommended for 1500 users
recommended for 2000 users
recommended for 2500 users
recommended for 3000 users
recommended for 3500 users
recommended for 4000 users
recommended for 4500 users
recommended for 5000 users
recommended for 5500 users
recommended for 6000 users
recommended for 6500 users
recommended for 7000 users
recommended for 7500 users
recommended for 8000 users
recommended for 8500 users
recommended for 9000 users
recommended for 9500 users
recommended for 10000 users
recommended for 10500 users
recommended for 11000 users
recommended for 11500 users
recommended for 12000 users
recommended for 12500 users
recommended for 13000 users
recommended for 13500 users
recommended for 14000 users
recommended for 14500 users
recommended for 15000 users
recommended for 15500 users
recommended for 16000 users
recommended for 16500 users
recommended for 17000 users
recommended for 17500 users
recommended for 18000 users
recommended for 18500 users
recommended for 19000 users
recommended for 19500 users
recommended for 20000 users
recommended for 20500 users
recommended for 21000 users
recommended for 21500 users
recommended for 22000 users
recommended for 22500 users
recommended for 23000 users
recommended for 23500 users
recommended for 24000 users
recommended for 24500 users
recommended for 25000 users
recommended for 25500 users
recommended for 26000 users
recommended for 26500 users
recommended for 27000 users
recommended for 27500 users
recommended for 28000 users
recommended for 28500 users
recommended for 29000 users
recommended for 29500 users
recommended for 30000 users
recommended for 30500 users
recommended for 31000 users
recommended for 31500 users
recommended for 32000 users
recommended for 32500 users
recommended for 33000 users
recommended for 33500 users
recommended for 34000 users
recommended for 34500 users
recommended for 35000 users
recommended for 35500 users
recommended for 36000 users
recommended for 36500 users
recommended for 37000 users
recommended for 37500 users
recommended for 38000 users
recommended for 38500 users
recommended for 39000 users
recommended for 39500 users
recommended for 40000 users
recommended for 40500 users
recommended for 41000 users
recommended for 41500 users
recommended for 42000 users
recommended for 42500 users
recommended for 43000 users
recommended for 43500 users
recommended for 44000 users
recommended for 44500 users
recommended for 45000 users
recommended for 45500 users
recommended for 46000 users
recommended for 46500 users
recommended for 47000 users
recommended for 47500 users
recommended for 48000 users
recommended for 48500 users
recommended for 49000 users
recommended for 49500 users
recommended for 50000 users
recommended for 50500 users
recommended for 51000 users
recommended for 51500 users
recommended for 52000 users
recommended for 52500 users
recommended for 53000 users
recommended for 53500 users
recommended for 54000 users
recommended for 54500 users
recommended for 55000 users
recommended for 55500 users
recommended for 56000 users
recommended for 56500 users
recommended for 57000 users
recommended for 57500 users
recommended for 58000 users
recommended for 58500 users
recommended for 59000 users
recommended for 59500 users
recommended for 60000 users
recommended for 60500 users
recommended for 61000 users
recommended for 61500 users
recommended for 62000 users
recommended for 62500 users
recommended for 63000 users
recommended for 63500 users
recommended for 64000 users
recommended for 64500 users
recommended for 65000 users
recommended for 65500 users
recommended for 66000 users
recommended for 66500 users
recommended for 67000 users
recommended for 67500 users
recommended for 68000 users
recommended for 68500 users
recommended for 69000 users
recommended for 69500 users
recommended for 70000 users
recommended for 70500 users
recommended for 71000 users
recommended for 71500 users
recommended for 72000 users
recommended for 72500 users
recommended for 73000 users
recommended for 73500 users
recommended for 74000 users
recommended for 74500 users
recommended for 75000 users
recommended for 75500 users
recommended for 76000 users
recommended for 76500 users
recommended for 77000 users
recommended for 77500 users
recommended for 78000 users
recommended for 78500 users
recommended for 79000 users
recommended for 79500 users
recommended for 80000 users
recommended for 80500 users
recommended for 81000 users
recommended for 81500 users
recommended for 82000 users
recommended for 82500 users
recommended for 83000 users
recommended for 83500 users
recommended for 84000 users
recommended for 84500 users
recommended for 85000 users
recommended for 85500 users
recommended for 86000 users
recommended for 86500 users
recommended for 87000 users
recommended for 87500 users
recommended for 88000 users
recommended for 88500 users
recommended for 89000 users
recommended for 89500 users
recommended for 90000 users
recommended for 90500 users
recommended for 91000 users
recommended for 91500 users
recommended for 92000 users
recommended for 92500 users
recommended for 93000 users
recommended for 93500 users
recommended for 94000 users
recommended for 94500 users
recommended for 95000 users
recommended for 95500 users
recommended for 96000 users
recommended for 96500 users
recommended for 97000 users
recommended for 97500 users
recommended for 98000 users
recommended for 98500 users
recommended for 99000 users
recommended for 99500 users
recommended for 100000 users
recommended for 100500 users
recommended for 101000 users
recommended for 101500 users
recommended for 102000 users
recommended for 102500 users
recommended for 103000 users
recommended for 103500 users
recommended for 104000 users
recommended for 104500 users
recommended for 105000 users
recommended for 105500 users
recommended for 106000 users
recommended for 106500 users
recommended for 107000 users
recommended for 107500 users
recommended for 108000 users
recommended for 108500 users
recommended for 109000 users
recommended for 109500 users
recommended for 110000 users
recommended for 110500 users
recommended for 111000 users
recommended for 111500 users
recommended for 112000 users
recommended for 112500 users
recommended for 113000 users
recommended for 113500 users
recommended for 114000 users
recommended for 114500 users
recommended for 115000 users
recommended for 115500 users
recommended for 116000 users
recommended for 116500 users
recommended for 117000 users
recommended for 117500 users
recommended for 118000 users
recommended for 118500 users
recommended for 119000 users
recommended for 119500 users
recommended for 120000 users
recommended for 120500 users
recommended for 121000 users
recommended for 121500 users
recommended for 122000 users
recommended for 122500 users
recommended for 123000 users
recommended for 123500 users
recommended for 124000 users
recommended for 124500 users
recommended for 125000 users
recommended for 125500 users
recommended for 126000 users
recommended for 126500 users
recommended for 127000 users
recommended for 127500 users
recommended for 128000 users
recommended for 128500 users
recommended for 129000 users
recommended for 129500 users
recommended for 130000 users
recommended for 130500 users
recommended for 131000 users
recommended for 131500 users
recommended for 132000 users
recommended for 132500 users
recommended for 133000 users
recommended for 133500 users
recommended for 134000 users
recommended for 134500 users
recommended for 135000 users
recommended for 135500 users
recommended for 136000 users
recommended for 136500 users
recommended for 137000 users
recommended for 137500 users
recommended for 138000 users
recommended for 138500 users
recommended for 139000 users
recommended for 139500 users
recommended for 140000 users
recommended for 140500 users
recommended for 141000 users
recommended for 141500 users
recommended for 142000 users
recommended for 142500 users
recommended for 143000 users
recommended for 143500 users
recommended for 144000 users
recommended for 144500 users
recommended for 145000 users

recommended for 145500 users
recommended for 146000 users
recommended for 146500 users
recommended for 147000 users
recommended for 147500 users
recommended for 148000 users
recommended for 148500 users
recommended for 149000 users
recommended for 149500 users
recommended for 150000 users
precision=0.0070	recall=0.1379	coverage=0.5394	popularity=2.2208

In [24]:
usercf_pred = UserBasedCF()

相似用户数目为 = 30
推荐Item数目为 = 30

In [25]:
usercf_pred.generate_dataset(merge_yy[['buyer_admin_id','item_id']],test[['buyer_admin_id','item_id']].drop_duplicates(subset=['buyer_admin_id'], keep='first'))

预测尝试！
split training set and test set succ
train set = 2399699
test set = 11398

In [26]:
usercf_pred.calc_user_sim()

构建物品-用户倒排表中，请等待......
构建物品-用户倒排表成功
总共被操作过的物品数目为 = 972388
building user co-rated items matrix...
build user co-rated items matrix succ
calculating user similarity matrix...
calculating user similarity factor(2000000)
calculating user similarity factor(4000000)
calculating user similarity factor(6000000)
calculating user similarity factor(8000000)
calculating user similarity factor(10000000)
calculating user similarity factor(12000000)
calculating user similarity factor(14000000)
calculating user similarity factor(16000000)
calculating user similarity factor(18000000)
calculating user similarity factor(20000000)
calculating user similarity factor(22000000)
calculating user similarity factor(24000000)
calculating user similarity factor(26000000)
calculate user similarity matrix(similarity factor) succ
Total similarity factor number = 27251402

In [27]:
output = open('usercf_pred.pkl', 'wb')
pickle.dump(usercf_pred, output)
output.close()

In [28]:
result = usercf_pred.predict()

Predict start...
recommended for 0 users
recommended for 500 users
recommended for 1000 users
recommended for 1500 users
recommended for 2000 users
recommended for 2500 users
recommended for 3000 users
recommended for 3500 users
recommended for 4000 users
recommended for 4500 users
recommended for 5000 users
recommended for 5500 users
recommended for 6000 users
recommended for 6500 users
recommended for 7000 users
recommended for 7500 users
recommended for 8000 users
recommended for 8500 users
recommended for 9000 users
recommended for 9500 users
recommended for 10000 users
recommended for 10500 users
recommended for 11000 users
Predict end...

In [29]:
result_df = pd.DataFrame(result,columns=['buyer_admin_id','rec_items'])
result_df['rec_items'] = result_df.rec_items.apply(lambda x:[i[0] for i in x])
result_df['len'] = result_df.rec_items.apply(lambda x:len(x))

In [30]:
result_df[result_df['len'] < 30].head()

     buyer_admin_id                                          rec_items  len
42           726476                                                 []    0
88          1896287  [956091, 2101539, 2104262, 2110417, 2116251, 2...   16
205          609047  [12928279, 12626807, 11717821, 12186473, 10945...   29
225          974416  [1578258, 2254804, 3589570, 6692791, 6721086, ...    8
338         1095440  [436805, 3712123, 6975923, 7753914, 7982327, 1...    7

In [31]:
popularity_check = usercf_pred.item_popular

In [32]:
popularity_check_sorted = sorted(popularity_check.items(), key=lambda obj: obj[1],reverse=True)

In [33]:
for i in range(30):
    result_df['predict '+str(i+1)] = result_df.rec_items.apply(lambda x:x[i] if len(x) >i else random.choice( popularity_check_sorted [:100])[0])

In [34]:
result_df[result_df['len']<20].head(2) # 已经填上了

,buyer_admin_id,rec_items,len,predict 1,predict 2,predict 3,predict 4,predict 5,predict 6,predict 7,...,predict 21,predict 22,predict 23,predict 24,predict 25,predict 26,predict 27,predict 28,predict 29,predict 30
42,726476,[],0,13018359,11559746,2249889,2953605,10788165,11526051,3362266,...,7223628,10517552,9789145,10617258,11291525,3086129,10342698,9841579,10342698,6025215
88,1896287,"[956091, 2101539, 2104262, 2110417, 2116251, 2...",16,956091,2101539,2104262,2110417,2116251,2134952,3659075,...,10538002,8081951,3866632,13038480,13040827,9414379,10342698,908415,10761081,2953605

In [35]:
result_df.buyer_admin_id.unique().shape # 跟测试集个数匹配

(11398,)

In [36]:
result_df.sort_values('buyer_admin_id').drop(['rec_items','len'],axis=1).to_csv('user_cf.csv',index=False,header=False)